server:
  port: 8080
  servlet:
    context-path: /interest
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #本地数据库
    url: jdbc:mysql://localhost:3306/interest?useUnicode=true&characterEncoding=UTF-8&amp;useSSL=false&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: wanghuan
  redis:
    #本地redis
    database: 4
    host: 127.0.0.1
    port: 6379
    password: null
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.model

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest: DEBUG