server:
  port: 8090
  servlet:
    context-path: /bishe
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/beshi?useUnicode=true&characterEncoding=UTF-8&amp;useSSL=false&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: wanghuan
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: null
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wanghuan.model

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.wanghuan: DEBUG